@startuml banco

' skinparam linetype ortho
hide circle


!$renderMeta = 1

!procedure $meta()
  !if $renderMeta
    * id: text
    * createdAt: datetime
    * updatedAt: datetime
  !else
  !endif
!endprocedure

entity "Distritos" as districts {
  $meta()
  --
  * name: text
  * municipalities: text[]
  * state: text
}

entity "Fóruns" as forums {
  $meta()
  * districtId: text (fk districts)
  --
  * name: text
}

entity "Tribunais" as courts {
  $meta()
  * forumId: text (fk forums)
  --
  * name: text
  * abbreviation: text
  * area: court_area
}

entity "Processo" as lawsuits {
  $meta()
  courtId: text (fk courts)
  --
  * cnj: text
  * status: text
  * area: lawsuit_area
  * instance: lawsuit_instance
}

entity "Movimentação" as movements {
  $meta()
  lawsuitId: text (fk lawsuits)
  --
  lawsuitCnj: text
  * type: text
  * title: text
  * description: text
  * showClient: boolean
  _judiceId: bigint
}

entity "Evento" as events {
  $meta()
  lawsuit_id: text (fk lawsuits)
  --
  type: text
  title: text
  description: text
  date: datetime
}

entity "Parte" as parties {
  $meta()
  entity_id: text (fk individual | legalEntity)
  lawsuit_id: text (fk lawsuits)
  --
  * type: entity_type
  role: part_role
}

enum "Tipo de Parte" as part_role {
  author
  defendant
}

enum "Tipo de Entidade" as entity_type {
  individual
  legal_entity
}

enum "Área do Tribunal" as court_area {
  civil
  criminal
  labor
  family
  public_finance
  small_claims
  electoral
  military
  juvenile
  environmental
  corporate
  penal_execution
}

entity "Testemunha" as witnesses {
  $meta()
  part_id: text (fk parties)
  individual_id: text (fk individuals)
  --
}

entity "Cliente" as clients {
  $meta()
  --
  * entityId: text (fk individual | legalEntity)
  * type: entity_type
}

entity "Pessoa física" as individuals {
  $meta()
  --
  * name: text
  * cpf: text
  birthDate: datetime
  gender: gender_type
  phones: text[]
  email: text
}

entity "Pessoa Jurídica" as legalEntities {
  $meta()
  --
  * corporateName: text
  * cnpj: text
}

entity "Documento do Cliente" as client_documents {
  $meta()
  client_id: text (fk clients)
  --
  type: text
  date: datetime
  description: text
  file_url: text
}

entity "Documento do Processo" as lawsuit_documents {
  $meta()
  lawsuit_id: text (fk lawsuits)
  movementation_id: text (fk movements)
  --
  type: text
  date: datetime
  description: text
  file_url: text
}

' Relationships
districts ||--o{ forums
forums ||--o{ courts
courts ||--o{ lawsuits

movements }o--|| lawsuits
events }o--|| lawsuits
parties }o--|| lawsuits

witnesses }o--|| parties
witnesses }o--|| individuals

clients .. individuals
clients .. legalEntities

parties .. individuals
parties .. legalEntities

parties -- part_role
parties -- entity_type

client_documents }o--|| clients
lawsuit_documents }o--|| lawsuits
lawsuit_documents }o--o| movements

@enduml